import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Building2, Sparkles, TrendingUp } from "lucide-react";

import { KanoTable } from "@/components/kano/KanoTable";
import { Button } from "@/components/ui/button";
import { demoAnalysis, DEMO_PRODUCT_NAME } from "@/data/demo-analysis";
import { useCurrentUser } from "@/hooks/useAuth";

export const Route = createFileRoute("/")({
  component: Landing,
});

function Landing() {
  const me = useCurrentUser();
  const ctaHref = me.data ? "/new" : "/api/auth/google";

  return (
    <div className="container py-16 md:py-24">
      <section className="mx-auto max-w-3xl text-center space-y-6">
        {/* Medallion */}
        <div className="flex justify-center mb-2">
          <div className="medallion w-[72px] h-[72px]">
            <div className="medallion__ring">
              <div className="medallion__glass">
                <div className="medallion__spec" />
              </div>
            </div>
          </div>
        </div>

        <p className="eyebrow">
          Kano Model · Dan Olsen's benefits-focused framing
        </p>

        <h1 className="text-[clamp(34px,5vw,56px)] leading-[1.08]">
          See what sets{" "}
          <em className="grad-text">you apart.</em>
        </h1>

        <p className="text-lg text-muted-foreground">
          Drop in a few competitor docs. KanoLens builds an interactive,
          fully-cited Kano comparison — Must-Haves, Performance Benefits,
          Delighters — in under a minute.
        </p>

        <div className="flex justify-center gap-3 pt-2 flex-wrap">
          {me.data ? (
            <Button asChild size="lg" className="btn-brand">
              <Link to="/new">
                Start an analysis <ArrowRight className="h-4 w-4" />
              </Link>
            </Button>
          ) : (
            <Button asChild size="lg" className="btn-brand">
              <a href={ctaHref}>
                Sign in to start <ArrowRight className="h-4 w-4" />
              </a>
            </Button>
          )}
        </div>
      </section>

      <section className="mt-20 grid gap-5 md:grid-cols-3" id="features">
        <FeatureCard
          icon={<Building2 />}
          eyebrow="Must-Have"
          title="Cited, not guessed"
          body="Every Yes/Maybe/No carries a source URL. Unsupported claims are marked Unverified."
        />
        <FeatureCard
          icon={<TrendingUp />}
          eyebrow="Performance"
          title="Benefits over features"
          body="Rows describe the customer benefit — saves time, reduces errors — not the raw feature."
        />
        <FeatureCard
          icon={<Sparkles />}
          eyebrow="Delighter"
          title="Streams as it builds"
          body="Watch rows populate live. Edit scope before the AI commits. No black boxes."
        />
      </section>

      {/* Demo preview */}
      <section className="mt-24 space-y-6">
        <div className="text-center space-y-2">
          <p className="eyebrow">Live example</p>
          <h2 className="text-2xl font-semibold">See what a KanoLens analysis looks like</h2>
          <p className="text-sm text-muted-foreground max-w-lg mx-auto">
            {DEMO_PRODUCT_NAME} vs. Linear, Jira &amp; Asana — generated by KanoLens.
          </p>
          <div className="pt-1">
            <Button asChild variant="outline" size="sm">
              <Link to="/example">
                Explore the full interactive example <ArrowRight className="h-3.5 w-3.5 ml-1" />
              </Link>
            </Button>
          </div>
        </div>

        <div className="relative">
          <KanoTable tableData={demoAnalysis} isLoading={false} />
          {/* Gradient overlay with sign-in CTA */}
          <div className="absolute bottom-0 left-0 right-0 h-64 bg-gradient-to-t from-background via-background/80 to-transparent flex flex-col items-center justify-end pb-8 gap-3 pointer-events-none">
            <p className="text-sm font-medium pointer-events-auto">Analyze your own product</p>
            {me.data ? (
              <Button asChild className="btn-brand pointer-events-auto">
                <Link to="/new">
                  Start an analysis <ArrowRight className="h-4 w-4" />
                </Link>
              </Button>
            ) : (
              <Button asChild className="btn-brand pointer-events-auto">
                <a href="/api/auth/google">
                  Sign in to get started <ArrowRight className="h-4 w-4" />
                </a>
              </Button>
            )}
          </div>
        </div>
      </section>
    </div>
  );
}

function FeatureCard({
  icon,
  eyebrow,
  title,
  body,
}: {
  icon: React.ReactNode;
  eyebrow: string;
  title: string;
  body: string;
}) {
  return (
    <div className="panel lift p-6 space-y-3">
      <div className="feature-ic">{icon}</div>
      <p className="eyebrow">{eyebrow}</p>
      <h3 className="text-base font-semibold">{title}</h3>
      <p className="text-sm text-muted-foreground">{body}</p>
    </div>
  );
}
